### ISSUE TITLE
`UnderlineNav2` incorrectly calculating nav area when moving pages.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [primer/react#2651]
### Description

It works fine to move to a page outside the more button, but if you move to a page inside the more button, the more button disappears.

https://user-images.githubusercontent.com/15520015/205739931-7145e7a8-9b76-449b-84de-e2137d7a3237.mov

### Steps to reproduce

1. Reduce window width to check more button
2. Open more and navigate to another page. After you do it a few times, it will be reproduced.

### Version

v35.15.1

### Browser

Chrome

**Comment by lesliecdubs** [comment]
@broccolinisoup might you be interested in looking into this in the next few weeks?

**Comment by broccolinisoup** [comment]
Sure @lesliecdubs! 

👋🏼 @b6pzeusbc54tvhw5jgpyw8pwz2x6gs, thanks for reporting this. I quickly tried it out but cannot reproduce it. Something worth mentioning though, we [released a change on v35.15.0](https://github.com/primer/react/releases/tag/v35.15.0) on the API for [exposing `aria-current` to the API and making the selected prop redundant for selected state](https://github.com/primer/react/pull/2618). We released this as a minor change because UnderlineNav2 is still `draft` and unfortunately we are experiencing an issue where some of our recent docs update couldn't make it to the [production](https://primer.style/react/) and UnderlineNav docs were affected by this issue. Apologise for this inconvenience, and we are working on fixing them. 

This is the updated docs : https://primer-afcff743b7-13348165.drafts.github.io/drafts/UnderlineNav2 If you could use `aria-current` to manage the selected state, I really hope you won't experience this issue 🤞🏼 If you have already updated your code before posting the issue or even using `aria-current` still causes the same problem, could I please ask more information like some code snippets etc? 

Thanks again for taking the time to report this!

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
After updating the react and nextjs packages to the latest version, the problem in the video above was not reproduced, but similar problems still occur. So I changed the title of this issue.

I made an example with codesandbox for reproduction, you can check it out here.

https://codesandbox.io/p/sandbox/primer-underline-nav2-bug-ojlgdh

https://user-images.githubusercontent.com/15520015/206830866-ba8e0e3a-f55d-4247-b195-c2775d822481.mov

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@broccolinisoup After updating the react and nextjs packages to the latest version, the problem in the video above was not reproduced, but similar problems still occur. So I changed the title of this issue.

I made an example with codesandbox for reproduction, you can check it out here.

https://codesandbox.io/p/sandbox/primer-underline-nav2-bug-ojlgdh

https://user-images.githubusercontent.com/15520015/206830866-ba8e0e3a-f55d-4247-b195-c2775d822481.mov

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Codesandbox was unstable, so I recreated it with stackblitz.

https://stackblitz.com/edit/primer-undelinenav2-issue-2651-2676

**Comment by broccolinisoup** [comment]
👋 @b6pzeusbc54tvhw5jgpyw8pwz2x6gs thanks so much for the stackblitz! That will be very helpful to debug. I'll look into this and see what is going on 👀

**Comment by broccolinisoup** [comment]
👋🏼 @b6pzeusbc54tvhw5jgpyw8pwz2x6gs I had time to look at the issue today and I believe the reason of the issue is `aria-current` not working properly in the Stackblitz setup. When there is no "selected" state (it is achieved by `aria-current`), the component behaves unexpectedly. As far as I debugged, the root cause is the route names were not updating properly for most of the link items. See the screenshot please.

![a screenshot to demonstrate how the route name for one of the UnderlineNav links is rendered on the page as `[tabName]` instead of `tabs/the_name_of_the_tab`](https://user-images.githubusercontent.com/1446503/210025704-e866e22a-090e-48b3-a808-2f1784113e19.png)

I quickly whipped up a working demo on top off the Stackblitz you shared. Here is the [link](https://stackblitz.com/edit/primer-undelinenav2-issue-2651-2676-5achws?file=components/MyUnderlineNav.jsx) and we documented this [on our primer.style docs](https://primer.style/react/drafts/UnderlineNav2#with-nextjs) as well. (Quick note, just realised a typo and will fix it up. It should be `as={Link}` not `s={Link}`). Let us know if you have further concerns around this. Thanks!

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@broccolinisoup Thanks for pointing out the bug in my code. I confirmed that the problem was solved in the stackblitz you shared. Thank you so much!

However, in my real project, which is not an example, the problem still occurs. I'm using a lot of different layouts for this project, but I think one of them is the problem. I'll check further on what's wrong and if I find reproducible code, I'll share it here in the comments.

So, can we leave this issue open for a while?

**Comment by broccolinisoup** [comment]
No worries! I am glad it was helpful. Yes, we can keep the issue open in the meantime.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Even after fixing the aria-current props bug, my real project still has this bug.

https://user-images.githubusercontent.com/15520015/210181458-5e184439-667a-474d-aac2-8dd5ff52ac8f.mov

The real project used react@17.0.2, next@12.3.4, @primer/react@35.16.0 and TypeScript.

However, it is not reproducible with the example code. Reproducing failed even though the packages and code of the example code were matched to the real project as much as possible. There are a few more attempts left, but when the next and react packages are updated in the real project, the bug does not occur, so I will close the issue here.

I'll come back again if there's anything to update. Thanks again!

**Comment by broccolinisoup** [comment]
No worries! Sorry to hear that there is still an issue in your real project. Please do let us know if you find a way to reproduce the issue again. Thanks for your time!
